### ISSUE TITLE
wallet: Panic when deleting dcr wallet.

### ISSUE THREAD

**Issue by JoeGruffins** [crypto-power/cryptopower#150]
Deleting a dcr wallet that was apparently syncing:
```
2023-10-05 13:07:24.020 [INF] DCR: The wallet has been unlocked without a time limit
2023-10-05 13:07:24.020 [INF] DCR: Canceling sync. May take a while for sync to fully cancel.
2023-10-05 13:07:24.020 [INF] DCR: Address manager shutting down
2023-10-05 13:07:24.024 [INF] DCR: Sync fully canceled.
2023-10-05 13:07:24.024 [INF] SHWL: (new wallet) full network shutdown protocols completed.
2023-10-05 13:07:24.026 [INF] SHWL: Deleting Wallet
2023-10-05 13:07:24.068 [ERR] DCR: Attempting to read best block timestamp without a loaded asset.
2023-10-05 13:07:28.852 [INF] UI: Internet connection has been established
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfaa6df]

goroutine 90 [running]:
decred.org/dcrwallet/v3/wallet.(*Wallet).Locked(...)
        /home/joe/go/pkg/mod/decred.org/dcrwallet/v3@v3.0.1/wallet/wallet.go:1909
decred.org/dcrwallet/v3/spv.NewSyncer(0x0, 0xc00b1b0280)
        /home/joe/go/pkg/mod/decred.org/dcrwallet/v3@v3.0.1/spv/sync.go:120 +0x1f
github.com/crypto-power/cryptopower/libwallet/assets/dcr.(*Asset).SpvSync(0xc002a3c750)
        /home/joe/git/cryptopower/libwallet/assets/dcr/sync.go:235 +0x6d8
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).startSyncing.func1()
        /home/joe/git/cryptopower/ui/page/root/home_page.go:488 +0x27a
created by github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).startSyncing in goroutine 39
        /home/joe/git/cryptopower/ui/page/root/home_page.go:477 +0x1a5
```

**Comment by JoeGruffins** [comment]
I'll try to reproduce again and then try to fix.

**Comment by JoeGruffins** [comment]
Apparently it's a known issue:
https://github.com/crypto-power/cryptopower/blob/6c05a8b9534dc13e278312597dc1f0d658a3f88f/libwallet/assets/dcr/sync.go#L445-L450

**Comment by JoeGruffins** [comment]
The panic spot:
https://github.com/decred/dcrwallet/blob/e71decbdc9b9462746a792b1790aa768129204f1/wallet/wallet.go#L1907-L1910

**Comment by JoeGruffins** [comment]
Called by NewSyncer, which shouldn't be called on a deleted wallet I assume:
https://github.com/decred/dcrwallet/blob/e71decbdc9b9462746a792b1790aa768129204f1/spv/sync.go#L116-L128

**Comment by JoeGruffins** [comment]
It looks like it happened because of the connect loop. I recently changed this a bit will look again to see if it is possible it is to continue with a deleted wallet.

https://github.com/crypto-power/cryptopower/blob/aa0f69516d91a6ca7aa989ca541bb364f67b5775/ui/page/root/home_page.go#L488

**Comment by JoeGruffins** [comment]
Ok can reproduce but its complicated. go back to 4b16f2eeafcd367662b86e9c3bb93fe4bf14f0f7 or so start a wallet sync with no internet then connect, delete the wallet, then connect back to the internet and that loop with call sync. This is mostly fixed by exiting on ctx.Done().

**Comment by JoeGruffins** [comment]
So a wallet can be accessed after it is deleted and you can call the dcrlib functions on it. I think this may need quite a few changes to make it so that it cannot ever panic. Anywhere a goroutine is used can potentially panic as it is now, I guess, if the wallet was deleted. Not sure the best way to fix atm. I guess all wallet functions need a read lock and creation/deletion needs a write lock.

**Comment by JoeGruffins** [comment]
@dreacot I don't want to make a lot of changes without your input, but I think having a function that looks like:
```
func (*h holder) DoWithWallet(f func(*wallet) error ) error {
    h.mtx.RLock()
    defer h.mtx.RUnlock()
    if !h.walletExists {
        return NoWalletErr
    }
    return f(h.wallet)
}
```

You would use this wherever you would use the wallet. Then create/delete will hold the same mutex's write lock. Let me know if that makes sense and seems like a good idea, to avoid using a wallet that does not exist.

**Comment by dreacot** [comment]
This doesn't sound like a bad idea, would cause a lot of refactoring, ideally shouldn't each wallet method check to confirm that a wallet isn't nil, e.g `if wallet == nil return`. might not be too effective though without a mutex lock

**Comment by JoeGruffins** [comment]
You need the mutex read locked for the entirety of use to avoid deleting during any of that time I believe.

**Comment by JoeGruffins** [comment]
I'll also wait for @itswisdomagain to comment before doing anything.

**Comment by itswisdomagain** [comment]
Discussed with @JoeGruffins. My coming libwallet refactor PR touches some of these, so let's wait for that and see how this can come into play then.

**Comment by JoeGruffins** [comment]
> Discussed with @JoeGruffins. My coming libwallet refactor PR touches some of these, so let's wait for that and see how this can come into play then.

Did this ever happen?

**Comment by dreacot** [comment]
@itswisdomagain were you able to get to the refactor?
