### ISSUE TITLE
while trying to backup wallet, clicking i have written all 33 seed words crashes the app

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#190]
![Image](https://github.com/crypto-power/cryptopower/assets/25265396/415f678c-f70b-4401-80f3-108c7fab1cac)

see crash log below

```
panic: runtime error: index out of range [-1]

goroutine 179 [running]:
github.com/crypto-power/cryptopower/ui/page/seedbackup.(*VerifySeedPage).getMultiSeed(0xc006403c00, 0xffffffffffffffff, {0xc0072a2000, 0x200, 0x200})
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/seedbackup/verify_seed.go:124 +0x86a
github.com/crypto-power/cryptopower/ui/page/seedbackup.(*VerifySeedPage).OnNavigatedTo(0xc006403c00)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/seedbackup/verify_seed.go:102 +0x2f1
github.com/crypto-power/cryptopower/app.(*PageStack).Push(0xc0036f7c50, {0x1f8b390, 0xc006403c00}, {0x1f8e0b0, 0xc0036f7c80})
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/app/pagestack.go:67 +0x538
github.com/crypto-power/cryptopower/app.(*SimpleWindowNavigator).Display(0xc0036f7c80, {0x1f8b390?, 0xc006403c00?})
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/app/window.go:49 +0x39
github.com/crypto-power/cryptopower/ui/page/seedbackup.(*SaveSeedPage).HandleUserInteractions(0xc007824000)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/seedbackup/save_seed.go:167 +0x8b
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc000189720, {{0xc1437b109bd47a0d, 0xe24f23dac, 0x2e7a220}, {0x3f800000, 0x3f800000}, {0x320, 0x28a}, {0x0, 0x0, ...}, ...})
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/window.go:233 +0x14c
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc000189720)
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/window.go:206 +0x2b9
main.main.func3()
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/main.go:110 +0x1d
created by main.main
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/main.go:108 +0x61b
exit status 2
```

**Comment by ukane-philemon** [comment]
@dreacot, how can I reproduce it? I just did a successful backup rn.

**Comment by dreacot** [comment]
> @dreacot, how can I reproduce it? I just did a successful backup rn.
> 
> EDIT: Just did. I had to use the backup btn on the wallet info page then cancelled the password modal before clicking the "I have written all 33 seed words" button.
> 
> With the fix in #185 we won't get in this situation.

this seems to happen only on a particular wallet, and it's also reproducible for that wallet on master

**Comment by ukane-philemon** [comment]
> this seems to happen only on a particular wallet,

Which wallet?

**Comment by dreacot** [comment]
One of my testnet decred wallets

**Comment by ukane-philemon** [comment]
Was the seed displayed after the providing the correct pass?

**Comment by dreacot** [comment]
> Was the seed displayed after the providing the correct pass?

yes it was

**Comment by dreacot** [comment]
not reproducible
