### ISSUE TITLE
[Mobile]: when creating a wallet, entering a value into the wallet name text field causes the app to crash

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#27]
<img src="https://github.com/crypto-power/cryptopower/assets/25265396/9702217f-e7ed-4593-b522-742213f031c2" height=500 />

see the crash log below:

```
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: panic: runtime error: slice bounds out of range [:40] with capacity 32
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: 
2023-07-17 11:36:57.223 14634-14661/com.dreacotgroup.cryptopower I/com.github.cryptopower: panic: runtime error: slice bounds out of range [:40] with capacity 32
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: goroutine 17 [running, locked to thread]:
2023-07-17 11:36:57.223 14634-14661/com.dreacotgroup.cryptopower I/com.github.cryptopower: 
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: gioui.org/app.(*editorState).Replace(0xacd762f4, {0x0, 0x0}, {0xae3f7b30, 0x1})
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: 	/home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20230118222818-e0cf570339bd/app/window.go:657 +0x444
2023-07-17 11:36:57.223 14634-0/com.dreacotgroup.cryptopower E/Go: gioui.org/app.(*callbacks).EditorReplace(0xacd762ac, {0x0, 0x0}, {0xae3f7b30, 0x1})
2023-07-17 11:36:57.224 14634-0/com.dreacotgroup.cryptopower E/Go: 	/home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20230118222818-e0cf570339bd/app/window.go:568 +0x50
2023-07-17 11:36:57.224 14634-0/com.dreacotgroup.cryptopower E/Go: gioui.org/app.Java_org_gioui_GioView_imeReplace(0xf2319400, 0xff8cd17c, 0x1, 0x0, 0x0, 0xff8cd180)
2023-07-17 11:36:57.224 14634-0/com.dreacotgroup.cryptopower E/Go: 	/home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20230118222818-e0cf570339bd/app/os_android.go:1090 +0xb2
    
    --------- beginning of crash
2023-07-17 11:36:57.224 14634-14634/com.dreacotgroup.cryptopower A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 14634 (oup.cryptopower), pid 14634 (oup.cryptopower)
```

**Comment by dreacot** [comment]
resolved by upgrading to the latest gio version https://github.com/crypto-power/cryptopower/pull/34
