### ISSUE TITLE
Crash when enable mixer

### ISSUE THREAD

**Issue by JustinBeBoy** [crypto-power/cryptopower#301]
App crash when enable mixer

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xc87d00]

goroutine 124 [running]:
gioui.org/gesture.(*Drag).Events(0xc0067dc318, {0x40?, 0x0?}, {0x0?, 0x0?}, 0x0)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/gesture/gesture.go:378 +0x40
github.com/crypto-power/cryptopower/ui/cryptomaterial.(*SliceAction).DragLayout(0xc0067dc270, {{{0x0, 0x0}, {0x2f0, 0x1ed}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/slide_action.go:69 +0x9b
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1.1.1.(*SegmentedControl).Layout.func2.2.1({{{0x0, 0x0}, {0x2f0, 0x1ed}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/segmented_control.go:88 +0x91
gioui.org/layout.Inset.Layout({0x4220?, 0x0?, 0xd8?, 0x0?}, {{{0x0, 0x0}, {0x2f0, 0x1ed}}, {0x3f800000, 0x3f800000}, ...}, ...)    
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1.1.1.(*SegmentedControl).Layout.func2.2({{{0x0, 0x0}, {0x2f0, 0x1fd}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/segmented_control.go:86 +0xb2
gioui.org/layout.Flex.Layout({0x0?, 0x0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x2f0, 0x21f}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/flex.go:99 +0x2d5
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1.1.1.(*SegmentedControl).Layout.func2({{{0x0, 0x0}, {0x2f0, 0x21f}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/segmented_control.go:78 +0x1bb
gioui.org/layout.Inset.Layout({0x390bca0?, 0xc0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x2f0, 0x21f}}, {0x3f800000, 0x3f800000}, ...}, ...) 
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/cryptomaterial.UniformPadding({{{0x0, 0x0}, {0x320, 0x24f}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/util.go:157 +0x1af
github.com/crypto-power/cryptopower/ui/cryptomaterial.(*SegmentedControl).Layout(...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/segmented_control.go:74
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1.1.1({{{0x0, 0x0}, {0x320, 0x24f}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:388 +0x105
gioui.org/layout.Inset.Layout({0x67517a0?, 0xc0?, 0x3f?, 0x0?}, {{{0x0, 0x0}, {0x320, 0x24f}}, {0x3f800000, 0x3f800000}, ...}, ...)        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1.1({{{0x0, 0x0}, {0x320, 0x25f}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:387 +0x89
gioui.org/layout.Flex.Layout({0xb?, 0x0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/flex.go:99 +0x2d5
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:88 +0x65
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:196 +0x155
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:87 +0xc6
gioui.org/layout.Inset.Layout({0x39cd658?, 0xc0?, 0xd9ed47?, 0x0?}, {{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:85 +0xe9
github.com/crypto-power/cryptopower/ui/cryptomaterial.Border.Layout({{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, 0x0}, {{{0x320, ...}, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/border.go:21 +0x98
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:83 +0x1b6
gioui.org/layout.Stack.Layout({0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/stack.go:60 +0x175
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:46 +0x2aa
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:105 +0x219
gioui.org/layout.Inset.Layout({0x7c?, 0x0?, 0x100?, 0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...)     
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:44 +0xe9
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:196 +0x155
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xfffffffffffffffe, 0x1, {0x0, 0x0, 
0x0, 0x0}, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:42 +0xe5
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop.func1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:382 +0x205
gioui.org/layout.Stack.Layout({0x0?}, {{{0x0, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/stack.go:78 +0x478
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).layoutDesktop(0xc003f6a360, {{{0x0, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:375 +0x12b
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).Layout(0x0?, {{{0x0, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:371 +0x38
gioui.org/layout.Flex.Layout({0x5?, 0x0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/flex.go:134 +0x735
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:88 +0x65
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:196 +0x155
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:87 +0xc6
gioui.org/layout.Inset.Layout({0x39cfb98?, 0xc0?, 0xd9ed47?, 0x0?}, {{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:85 +0xe9
github.com/crypto-power/cryptopower/ui/cryptomaterial.Border.Layout({{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, 0x0}, {{{0x320, ...}, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/border.go:21 +0x98
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1.2({{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:83 +0x1b6
gioui.org/layout.Stack.Layout({0xaf?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/stack.go:60 +0x175
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:46 +0x2aa
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:105 +0x219
gioui.org/layout.Inset.Layout({0x3f40500?, 0xc0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, ...}, ...) 
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:169 +0x39a
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:44 +0xe9
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/layout.go:196 +0x155
github.com/crypto-power/cryptopower/ui/cryptomaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xfffffffffffffffe, 0x1, {0x0, 0x0, 
0x0, 0x0}, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        D:/Works/Decred/cryptopower/ui/cryptomaterial/linearlayout.go:42 +0xe5
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).layoutDesktop.func1({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/home_page.go:378 +0x265
gioui.org/layout.Stack.Layout({0x0?}, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/stack.go:78 +0x478
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).layoutDesktop(0xc003fbe000, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/home_page.go:372 +0x12b
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).Layout(0x0?, {{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, 
{0x0, 0x0}, {0xc1524d172f06ac64, ...}, ...})
        D:/Works/Decred/cryptopower/ui/page/root/home_page.go:368 +0x78
github.com/crypto-power/cryptopower/ui.(*Window).prepareToDisplayUI.func2({{{0x0, 0x0}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, 
{0x0, 0x0}, {0xc1524d172f06ac64, 0x4702f36d1, ...}, ...})
        D:/Works/Decred/cryptopower/ui/window.go:284 +0x11c
gioui.org/layout.Stack.Layout({0xa0?}, {{{0x320, 0x28a}, {0x320, 0x28a}}, {0x3f800000, 0x3f800000}, {0x24a1b40, 0xc000c8ccc8}, {0xc1524d172f06ac64, ...}, ...}, ...)
        C:/Users/namdn/go/pkg/mod/gioui.org@v0.1.0/layout/stack.go:60 +0x175
github.com/crypto-power/cryptopower/ui.(*Window).prepareToDisplayUI(0xc003086e10, {{0xc1524d172f06ac64, 0x4702f36d1, 0x31e1fc0}, {0x3f800000, 0x3f800000}, {0x320, 0x28a}, {0x0, 0x0, ...}, ...})
        D:/Works/Decred/cryptopower/ui/window.go:299 +0x3ed
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc003086e10, {{0xc1524d172f06ac64, 0x4702f36d1, 0x31e1fc0}, {0x3f800000, 0x3f800000}, {0x320, 0x28a}, {0x0, 0x0, ...}, ...})
        D:/Works/Decred/cryptopower/ui/window.go:237 +0x26a
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc003086e10)
        D:/Works/Decred/cryptopower/ui/window.go:200 +0x236
main.main.func3()
        D:/Works/Decred/cryptopower/main.go:109 +0x17
created by main.main in goroutine 1
        D:/Works/Decred/cryptopower/main.go:107 +0x4e9
exit status 2
```

**Comment by JustinBeBoy** [comment]
This problem only occurs in PR #256
