### ISSUE TITLE
app crashes when voting on proposal

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#53]
Clicking the "Vote" button crashes the app

<img width="360" alt="Screenshot 2023-08-28 at 3 38 02 PM" src="https://github.com/crypto-power/cryptopower/assets/25265396/49125c4f-935e-4845-b83f-55adc6ca23f5">

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x102cc8360]

goroutine 30 [running]:
github.com/crypto-power/cryptopower/ui/page/governance.(*voteModal).sendVotes.func1(...)
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/ui/page/governance/proposal_vote_modal.go:137
github.com/crypto-power/cryptopower/ui/page/governance.(*voteModal).sendVotes(0x14002590000)
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/ui/page/governance/proposal_vote_modal.go:145 +0x1b0
github.com/crypto-power/cryptopower/ui/page/governance.(*voteModal).Handle(0x14002590000)
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/ui/page/governance/proposal_vote_modal.go:198 +0x174
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0x14002622140, {{0xc1333d54b55a9d78, 0x11105d4c2a, 0x104444820}, {0x40000000, 0x40000000}, {0x640, 0x4b0}, {0x0, 0x0, ...}, ...})
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/ui/window.go:231 +0xf0
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0x14002622140)
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/ui/window.go:202 +0x1c0
main.main.func3()
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/main.go:110 +0x20
created by main.main in goroutine 1
        /Users/kennedy/go/src/github.com/crypto-power/cryptopower/main.go:108 +0x4a4
exit status 2
```

**Comment by dmigwi** [comment]
Below is the messy implementation that is causing the crash. Something seems off with it but I can fix it because I don't have enough coins on mainnet to test the proposal voting:

```go
func (vm *voteModal) sendVotes() {
	vm.detailsMu.Lock()
	tickets := vm.voteDetails.EligibleTickets
	vm.detailsMu.Unlock()

	votes := make([]*libwallet.ProposalVote, 0)
	addVotes := func(bit string, count int) {
		for i := 0; i < count; i++ {

			// get and pop
			tickets = tickets[1:]

			vote := &libwallet.ProposalVote{}
			vote.Ticket.Hash = tickets[0].Hash
			vote.Ticket.Address = tickets[0].Address
			vote.Bit = bit

			votes = append(votes, vote)
		}
	}

	addVotes(libwallet.VoteBitYes, vm.yesVote.voteCount())
	addVotes(libwallet.VoteBitNo, vm.noVote.voteCount())
...
```
@dreacot  how easy is it to request the decred team create another proposal ready for voting on testnet?
