### ISSUE TITLE
App crash when create new account

### ISSUE THREAD

**Issue by bugjt** [crypto-power/cryptopower#572]
When I created a new account, the app crashed!
<img width="803" alt="image" src="https://github.com/user-attachments/assets/239d178e-972f-4b2d-8c18-eb417fc7320c">
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/91289bc5-3769-455d-8824-2a98143b68c2">

**Comment by dreacot** [comment]
Can you copy and paste the logs?

**Comment by JustinBeBoy** [comment]
app crash when sync BTC too

```
2024-07-16 23:16:06.042 [INF] DCR: Discovering used addresses for 1 account(s)
2024-07-16 23:16:06.125 [INF] DCR: Account 0 next child indexes: external:2 internal:23
2024-07-16 23:16:06.134 [INF] DCR: Updating DB with discovered addresses...
2024-07-16 23:16:06.183 [INF] DCR: Finished address discovery
2024-07-16 23:16:06.183 [INF] SHWL: Set discovered accounts = true for wallet 10
2024-07-16 23:16:06.198 [INF] DCR: Loading active addresses and unspent outputs...
2024-07-16 23:16:06.203 [INF] DCR: Registered for transaction notifications for 65 HD address(es)
2024-07-16 23:16:06.206 [INF] DCR: Registered for transaction notifications for all relevant outputs
2024-07-16 23:16:06.206 [INF] DCR: Rescanning block range [1432803, 1432809]...
2024-07-16 23:16:06.222 [INF] DCR: Rescan complete
2024-07-16 23:16:06.222 [INF] DCR: [10] Indexing transactions start height: 1432760, end height: 1432809
2024-07-16 23:16:06.222 [INF] DCR: [10] Transaction index finished at 1432809, 16 transaction(s) indexed in total
2024-07-16 23:16:12.302 [INF] BTC: Fetching block height=2683623 hash=000000000000289b321c1a406a0a24c01dcdd0d50d3e6b8a1b4d320f3c7d8133
2024-07-16 23:16:12.754 [INF] BTC: Recovered addresses from blocks 2681650-2683649
2024-07-16 23:16:12.833 [INF] BTC: Scanning 2000 blocks for recoverable addresses
2024-07-16 23:16:12.837 [INF] BTC: Fetching block height=2683659 hash=00000000000018147d0dc0d439d874721d2ee4ff0b0d97f8fd6ec941976d03cb
2024-07-16 23:16:12.883 [INF] BTC: Canceling sync. May take a while for sync to fully cancel.
2024-07-16 23:16:12.883 [INF] BTC: (b1) SPV wallet closed
2024-07-16 23:16:12.987 [INF] BTC: Stopping (b1) wallet and its neutrino interface
2024-07-16 23:16:13.508 [INF] BTC: Synchronizing wallet (b1) with network...
2024-07-16 23:16:13.508 [ERR] BTC: Neutrino rescan ended with error: rescan block subscription was canceled
2024-07-16 23:16:14.510 [INF] BTC: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=200
2024-07-16 23:16:14.514 [INF] BTC: Seed birthday surpassed, starting recovery of wallet from height=2685650 hash=0000000000002c892e340af1e7b4249837679474afe297536fed50f4d2a146a9 with recovery-window=200
panic: unable to synchronize wallet to chain: unable to perform wallet recovery: failed to store sync information 0000000000002c892e340af1e7b4249837679474afe297536fed50f4d2a146a9: failed to fetch block hash for height 2685649: block not found

goroutine 7052 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0x14000cb4c60)
        /Users/justindo/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.9/wallet/chainntfns.go:117 +0xcf0
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC in goroutine 7035
        /Users/justindo/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.9/wallet/wallet.go:213 +0x388
```

**Comment by bugjt** [comment]
> Can you copy and paste the logs?

Here is some logs:
2024-07-19 17:23:01.816 [INF] DCR: Rescanning block range [928001, 930000]...
2024-07-19 17:23:01.839 [INF] DCR: Rescanning block range [930001, 932000]...
2024-07-19 17:23:01.865 [INF] DCR: Rescanning block range [932001, 934000]...
2024-07-19 17:23:02.342 [INF] DCR: Rescanning block range [934001, 936000]...
2024-07-19 17:23:02.378 [INF] DCR: Rescanning block range [936001, 938000]...
2024-07-19 17:23:02.404 [INF] DCR: Rescanning block range [938001, 940000]...
2024-07-19 17:23:02.429 [INF] DCR: Rescanning block range [940001, 942000]...
2024-07-19 17:23:02.454 [INF] DCR: Rescanning block range [942001, 944000]...
2024-07-19 17:23:02.742 [INF] DCR: Rescanning block range [944001, 946000]...
2024-07-19 17:23:03.013 [INF] DCR: Rescanning block range [946001, 948000]...
2024-07-19 17:23:03.049 [INF] BTC: Fetching block height=1879778 hash=0000000000038802c6e58a523f41750ec0bd0b75b15dfda9a24a4a47f5896f44
2024-07-19 17:23:03.295 [INF] DCR: Rescanning block range [948001, 950000]...
2024-07-19 17:23:03.307 [INF] BTC: Recovered addresses from blocks 1878001-1880000
2024-07-19 17:23:03.323 [INF] DCR: Rescanning block range [950001, 952000]...
2024-07-19 17:23:03.326 [INF] BTC: The wallet has been locked
panic: unable to synchronize wallet to chain: unable to perform wallet recovery: recovery: forced shutdown

goroutine 257 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0x14000938a20)
        /Volumes/Storages/Projects/cryptopower/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:117 +0xd84
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC in goroutine 192
        /Volumes/Storages/Projects/cryptopower/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:213 +0x364
exit status 2

**Comment by dreacot** [comment]
This crash should be resolved with the btc upgrade PR

**Comment by bugjt** [comment]
It seems to have been resolved, i don't see it occurring again
