### ISSUE TITLE
App crash when received new tx or block

### ISSUE THREAD

**Issue by JustinBeBoy** [crypto-power/cryptopower#604]
seem like some property in dropdown nil when tx or block update

```
2024-07-27 23:21:35.009 [ERR] B-NTR: Could not write filters to filterDB: need batch
2024-07-27 23:21:38.297 [ERR] DCR-S: Failed to get init state: policy violation: disconnecting from straggler peer (peer height 1440258, tip height 1440279)
2024-07-27 23:27:00.195 [ERR] B-NTR: Unable to parse IP network for peer d2of5vzfe772fq3oo6jnh32vqxwhshoua3t6shm2vpmfokpf73542jad.onion:18333: unsupported IP type
2024-07-27 23:27:01.355 [ERR] B-NTR: Unable to parse IP network for peer ktzfkunfxehdwrzr63gq5uj6toyv7zs66kexhtde6nctroyewz6fxpad.onion:18333: unsupported IP type
2024-07-27 23:34:55.816 [ERR] B-NTR: Unable to parse IP network for peer jkssuums7kzdhkkcloe6lglfxoozmtb56gkqbgkhsab4r35hostygtad.onion:18333: unsupported IP type
2024-07-27 23:52:25.824 [ERR] B-NTR: Unable to parse IP network for peer un7njhxuchraf5ioitidnjnhty7hqiicj344dka5fu5d6uzll44pybqd.onion:18333: unsupported IP type
2024-07-28 00:00:04.028 [ERR] B-NTR: Unable to parse IP network for peer jrhpwqahjrj75gtb7gt23eve65x7bbawy7j4edhmgbo5nj2mkaeghbyd.onion:18333: unsupported IP type
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x120 pc=0x1012f3258]

goroutine 129716 [running]:
github.com/crypto-power/cryptopower/ui/page/components.(*WalletDropdown).getWalletByID(...)
        /Users/justindo/Works/cryptopower/ui/page/components/wallet_dropdown.go:167
github.com/crypto-power/cryptopower/ui/page/components.(*WalletDropdown).Setup(0x140004e2070)
        /Users/justindo/Works/cryptopower/ui/page/components/wallet_dropdown.go:62 +0x698
github.com/crypto-power/cryptopower/ui/page/components.(*WalletDropdown).ListenForTxNotifications.func2(0x102de0fa0?, 0x1ed2d790?)
        /Users/justindo/Works/cryptopower/ui/page/components/wallet_dropdown.go:238 +0x50
created by github.com/crypto-power/cryptopower/libwallet/assets/dcr.(*Asset).publishBlockAttached in goroutine 7034
        /Users/justindo/Works/cryptopower/libwallet/assets/dcr/txandblocknotifications.go:141 +0x15c
exit status 2
```

**Comment by dreacot** [comment]
is this reproducible?

**Comment by JustinBeBoy** [comment]
> is this reproducible?

let me try, will tell you later

**Comment by JustinBeBoy** [comment]
closed because it cannot be reproduced

**Comment by JustinBeBoy** [comment]
2024-08-22 14:04:38.587 [INF] DCR: Returning address (account=0 branch=1 child=29797)
2024-08-22 14:04:38.593 [INF] DCR: The wallet has been locked due to timeout.
2024-08-22 14:04:38.600 [INF] DCR: Returning address (account=0 branch=1 child=29798)
2024-08-22 14:06:59.978 [INF] DCR: Returning address (account=0 branch=1 child=29799)
2024-08-22 14:19:49.198 [INF] DCR: The wallet has been unlocked without a time limit
2024-08-22 14:19:49.198 [INF] DCR: Cancelling sync. May take a while for sync to fully cancel.
2024-08-22 14:19:49.199 [INF] DCR: Address manager shutting down
2024-08-22 14:19:49.199 [INF] DCR: Sync fully cancelled.
2024-08-22 14:19:49.199 [ERR] DCR: [5] Get tx indexing start point error: database not open
2024-08-22 14:19:49.199 [ERR] DCR: Tx Index Error: database not open
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1f0 pc=0x103772b1c]

goroutine 322278 [running]:
github.com/crypto-power/cryptopower/libwallet/assets/dcr.(*Asset).listenForTransactions.func1()
        /Users/justindo/Works/cryptopower/libwallet/assets/dcr/txandblocknotifications.go:11 +0x4c
created by github.com/crypto-power/cryptopower/libwallet/assets/dcr.(*Asset).listenForTransactions in goroutine 400
        /Users/justindo/Works/cryptopower/libwallet/assets/dcr/txandblocknotifications.go:10 +0x5c
exit status 2

**Comment by JoeGruffins** [comment]
Maybe the same issue as  #150

If you delete a wallet that something is using asynchronously there will be a panic. There are probably a lot of ways in which this can happen.
