### ISSUE TITLE
App crash when click to manual setup in stakeshuffle page

### ISSUE THREAD

**Issue by JustinBeBoy** [crypto-power/cryptopower#609]
App crash when click to manual setup in stakeshuffle page

```
2024-08-01 14:30:36.181 [INF] DCR: The wallet has been unlocked without a time limit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x101f6c5c4]

goroutine 67 [running]:
github.com/crypto-power/cryptopower/ui/page/components.(*AccountDropdown).SelectedAccount(...)
        /Users/justindo/Works/cryptopower/ui/page/components/account_dropdown.go:153
github.com/crypto-power/cryptopower/ui/page/privacy.NewManualMixerSetupPage.func2(0x1400677c480)
        /Users/justindo/Works/cryptopower/ui/page/privacy/manual_mixer_setup_page.go:56 +0x44
github.com/crypto-power/cryptopower/ui/page/components.(*AccountDropdown).Setup(0x14003053860, {0x102c14020?, 0x14000614180?})
        /Users/justindo/Works/cryptopower/ui/page/components/account_dropdown.go:52 +0x164
github.com/crypto-power/cryptopower/ui/page/privacy.NewManualMixerSetupPage(0x14000c8c050, 0x14000614180)
        /Users/justindo/Works/cryptopower/ui/page/privacy/manual_mixer_setup_page.go:70 +0x3b4
github.com/crypto-power/cryptopower/ui/page/privacy.(*SetupMixerAccountsPage).HandleUserInteractions(0x140066ad900, {{{0x900, 0x796}, {0x900, 0x796}}, {0x40000000, 0x40000000}, {0xc1a2ec4800e14bc8, 0x121e128480, 0x103b0a560}, ...})
        /Users/justindo/Works/cryptopower/ui/page/privacy/setup_mixer_accounts_page.go:204 +0x458
github.com/crypto-power/cryptopower/ui/page/wallet.(*SingleWalletMasterPage).HandleUserInteractions(0x1400013f688, {{{0x900, 0x796}, {0x900, 0x796}}, {0x40000000, 0x40000000}, {0xc1a2ec4800e14bc8, 0x121e128480, 0x103b0a560}, ...})
        /Users/justindo/Works/cryptopower/ui/page/wallet/single_wallet_main_page.go:287 +0xf8
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).HandleUserInteractions(0x140004a5d40, {{{0x900, 0x796}, {0x900, 0x796}}, {0x40000000, 0x40000000}, {0xc1a2ec4800e14bc8, 0x121e128480, 0x103b0a560}, ...})
        /Users/justindo/Works/cryptopower/ui/page/root/home_page.go:370 +0xf8
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0x140004ec1e0, {{0xc1a2ec4800e14bc8, 0x121e128480, 0x103b0a560}, {0x40000000, 0x40000000}, {0x900, 0x796}, {0x0, 0x0, ...}, ...})
        /Users/justindo/Works/cryptopower/ui/window.go:252 +0x1dc
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0x140004ec1e0)
        /Users/justindo/Works/cryptopower/ui/window.go:222 +0x26c
main.main.func4()
        /Users/justindo/Works/cryptopower/main.go:121 +0x20
created by main.main in goroutine 1
        /Users/justindo/Works/cryptopower/main.go:119 +0x3a4
exit status 2
```

**Comment by JustinBeBoy** [comment]
duplicate #607
