### ISSUE TITLE
Crash while looking through settings 

### ISSUE THREAD

**Issue by Vanvians** [crypto-power/cryptopower#61]
Application crashed while I was in settings. Clicked every non-toggle switch option, crash occurred when "View Application Log" clicked.
Logs-
```2023-09-08 18:19:51.839 [INF] DCR: Rescanning block range [788001, 790000]...
2023-09-08 18:19:51.858 [INF] DCR: Rescanning block range [790001, 792000]...
2023-09-08 18:19:53.082 [INF] DCR: Rescanning block range [792001, 794000]...
2023-09-08 18:19:53.102 [INF] DCR: Rescanning block range [794001, 796000]...
2023-09-08 18:19:53.121 [INF] DCR: Rescanning block range [796001, 797538]...
2023-09-08 18:19:53.135 [INF] DCR: Rescan complete
2023-09-08 18:19:53.135 [INF] DCR: [1] Indexing transactions start height: 0, end height: 797538
2023-09-09 01:40:08.658 [ERR] UI: Error adding tx and block notification listener: listener_already_exist
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xcdefc1]

goroutine 7150105 [running]:
github.com/crypto-power/cryptopower/ui/page/settings.(*LogPage).watchLogs.func1()
        C:/Users/jceze/cryptopower/ui/page/settings/log_page.go:107 +0x285
created by github.com/crypto-power/cryptopower/ui/page/settings.(*LogPage).watchLogs
        C:/Users/jceze/cryptopower/ui/page/settings/log_page.go:80 +0x56```

**Comment by Vanvians** [comment]
Unable to recreate Issue.
