### ISSUE TITLE
app crashed while listening for Orderbook Notifications

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#690]
i just had the app running in the background and came back to this crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x105cfb3c8]

goroutine 2373 [running]:
github.com/crypto-power/cryptopower/ui/page/dcrdex.(*DEXMarketPage).listenForOrderbookNotifications(0x14006066000)
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/page/dcrdex/market.go:454 +0x78
github.com/crypto-power/cryptopower/ui/page/dcrdex.(*DEXMarketPage).fetchOrderBook.func1()
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/page/dcrdex/market.go:432 +0x174
created by github.com/crypto-power/cryptopower/ui/page/dcrdex.(*DEXMarketPage).fetchOrderBook in goroutine 1798
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/page/dcrdex/market.go:423 +0x2b8
exit status 2
```

**Comment by dreacot** [comment]
resolved by https://github.com/crypto-power/cryptopower/pull/692
