### ISSUE TITLE
Persistent crash 

### ISSUE THREAD

**Issue by Vanvians** [crypto-power/cryptopower#76]
Application crashes everytime it is opened. Throwing this error code.

```
2023-09-24 12:48:43.058 [INF] POLT: Politeia sync: started
panic: unable to synchronize wallet to chain: unable to perform wallet recovery: couldn't retrieve block 971808fc981874b133c7ee1da399aae2c2161f675a8efeb4f1a1894c158599e7 from network

goroutine 84 [running]:
github.com/ltcsuite/ltcwallet/wallet.(*Wallet).handleChainNotifications(0xc00207e6c0)
        C:/Users/jceze/go/pkg/mod/github.com/ltcsuite/ltcwallet@v0.13.1/wallet/chainntfns.go:117 +0xfd3
created by github.com/ltcsuite/ltcwallet/wallet.(*Wallet).SynchronizeRPC in goroutine 62
        C:/Users/jceze/go/pkg/mod/github.com/ltcsuite/ltcwallet@v0.13.1/wallet/wallet.go:211 +0x249 
```

**Comment by Vanvians** [comment]
Issue with Vscode. Resolved after restart.
